image: node:14

definitions:
  steps:
    - step: &build-test
        name: Lint, Test and Test Build
        script:
          - yarn
          - yarn eslint-check && yarn prettier-check
          - yarn build
        services:
          - postgres-test

pipelines:
  pull-requests:
    "**":
      - step: *build-test
    "{feature,story,bugfix}/*":
      - step: *build-test
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - chmod +x ./scripts/staging/deploy.sh
            - ./scripts/staging/deploy.sh $(cut -d'/' -f2 <<<$BITBUCKET_BRANCH | tr '[:upper:]' '[:lower:]')
  branches:
    development:
      - step: *build-test
      - step:
          name: 'Push changes back to github'
          script:
            - git config user.name "Mike Pham"
            - git config user.email "31090859+mike-fam@users.noreply.github.com"
            - git remote add github git@github.com:mike-fam/tutor-timetable-v2.git
            - git push github development:main
      - step:
          name: 'Deployment to Production'
          deployment: production
          trigger: 'manual'
          script:
            - chmod +x ./scripts/production/deploy.sh
            - ./scripts/production/deploy.sh
