version: "3.7"

services:
  dev:
    image: node:latest
    command: bash -c '
      apt-get update &&
      apt-get install -y netcat &&
      chmod +x ./wait-for-it.sh &&
      ./wait-for-it.sh postgres:5432 -- yarn migration-run &&
      yarn dev'
    ports:
      - 3000:3000
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    volumes:
      - q-postgres:/var/lib/postgresql/data
      - ./bootstrap/data:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 5430:5432
    env_file: .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PW}"
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6378:6379
volumes:
  q-postgres:
